

import React, { createContext, useState, useContext, ReactNode, useCallback } from 'react';
import type { SignalType } from '../types';

const translations = {
  pt: {
    header_wallet_balance: "VTX",
    header_sign_out: "Sair",
    header_search_placeholder: "Pesquisar no APOLO...",
    dashboard_title: "Painel APOLO",
    dashboard_reset: "Resetar",
    dashboard_min_trust: "Pontuação Mín. de Confiança:",
    dashboard_signal_types: "Tipos de Sinal",
    dashboard_token_tags: "Tags de Token",
    signal_type_NEWS: "Notícias",
    signal_type_ON_CHAIN: "On-Chain",
    signal_type_PROJECT_UPDATE: "Atualização de Projeto",
    signal_type_RUMOR: "Rumor",
    signal_type_SOCIAL_SENTIMENT: "Sentimento Social",
    create_signal_title_placeholder: "Título do Sinal...",
    create_signal_content_placeholder: "Qual é o sinal, {name}?",
    create_signal_tags_placeholder: "Adicione tags de token... (ex: BTC, ETH, SOL)",
    create_signal_post_button: "Postar Sinal",
    create_signal_analyzing_button: "Postando...",
    feed_loading: "Carregando feed de notícias...",
    feed_no_signals: "Nenhum sinal corresponde aos seus filtros atuais.",
    feed_reset_filters: "Resetar Filtros",
    error_fetch_feed: "Falha ao buscar o feed de notícias. Por favor, tente novamente.",
    error_ai_analysis: "A análise de IA falhou. Por favor, tente novamente.",
    error_follow_update: "Falha ao atualizar o status de seguir. Tente novamente.",
    error_post_signal: "Falha ao postar o sinal. Tente novamente.",
    error_post_comment: "Falha ao postar o comentário. Tente novamente.",
    error_like_update: "Falha ao atualizar a curtida. Tente novamente.",
    error_repost_update: "Falha ao atualizar o repost. Tente novamente.",
    error_delete_signal: "Falha ao deletar o sinal. Tente novamente.",
    error_translation_failed: "A tradução falhou. Por favor, tente novamente mais tarde.",
    signal_card_trust_score: "Pontuação de Confiança",
    signal_card_integrity_breakdown: "Detalhes da Integridade:",
    signal_card_manipulation_risk: "Risco de Manipulação",
    signal_card_scam_potential: "Potencial de Golpe",
    signal_card_factuality: "Factualidade",
    signal_card_verified_sources: "Fontes Verificadas",
    signal_card_analyzing: "Análise de integridade em andamento...",
    signal_card_request_analysis: "Solicitar Análise de Integridade",
    signal_card_delete_button: "Deletar",
    signal_card_delete_confirm: "Você tem certeza que quer deletar este sinal? Esta ação não pode ser desfeita.",
    signal_card_translate_button: "Traduzir",
    signal_card_complex_analysis: "Análise complexa recebida",
    translating: "Traduzindo...",
    trending_title: "Tendências",
    modal_signal_details_title: "Detalhes do Sinal",
    modal_comments_title: "Comentários",
    modal_reply_placeholder: "Poste sua resposta...",
    modal_reply_button: "Responder",
    modal_replying_to: "Respondendo a",
    modal_cancel_reply: "cancelar",
    delete_modal_title: "Confirmar Exclusão",
    delete_modal_message: "Esta ação não pode ser desfeita. Isso irá excluir permanentemente o sinal.",
    delete_modal_confirm: "Excluir",
    delete_modal_cancel: "Cancelar",
    profile_follow: "Seguir",
    profile_following: "Seguindo",
    profile_followers: "Seguidores",
    profile_posts: "Sinais",
    profile_edit: "Editar Perfil",
    profile_view_button: "Ver Perfil",
    profile_back_to_feed: "Voltar ao Feed",
    profile_following_stat: "Seguindo",
    profile_no_signals_yet: "{handle} ainda não postou nenhum sinal.",
    profile_follows_you: "Segue você",
    feed_tab_for_you: "Para Você",
    feed_tab_following: "Seguindo",
    feed_following_empty_title: "Seu feed está quieto...",
    feed_following_empty_subtitle: "Siga criadores para ver os sinais deles aqui.",
    feed_following_no_posts_title: "Nenhuma novidade por enquanto",
    feed_following_no_posts_subtitle: "As pessoas que você segue ainda não postaram nada.",
    notifications_title: "Notificações",
    notifications_empty: "Você ainda não tem notificações.",
    notifications_clear_all: "Limpar Tudo",
    notification_like: "curtiu seu sinal:",
    notification_comment: "comentou no seu sinal:",
    notification_follow: "começou a seguir você.",
    enhancer_button: "Melhorar com IA",
    enhancer_button_enhancing: "Melhorando...",
    enhancer_title: "Assistente de Sinal IA",
    enhancer_description: "Aqui estão algumas sugestões da IA baseadas na sua ideia. Escolha uma para refinar seu sinal.",
    enhancer_use_suggestion: "Usar esta sugestão",
    enhancer_error: "Falha ao obter sugestões da IA. Por favor, tente novamente.",
    auth_welcome_title: "Bem-vindo ao APOLO",
    auth_welcome_subtitle: "A rede de integridade cripto. Faça login para continuar.",
    auth_email_label: "Email",
    auth_password_label: "Senha",
    auth_login_button: "Entrar",
    auth_signup_button: "Criar Conta",
    auth_toggle_to_signup: "Não tem uma conta?",
    auth_toggle_to_login: "Já tem uma conta?",
    auth_name_label: "Nome e Sobrenome",
    auth_handle_label: "Nome de Usuário (@)",
    auth_error_generic: "Ocorreu um erro. Por favor, tente novamente.",
    auth_error_invalid_credentials: "Credenciais inválidas. Por favor, verifique seu usuário e senha.",
    auth_error_handle_in_use: "Este nome de usuário já está em uso.",
    auth_error_weak_password: "A senha deve ter pelo menos 6 caracteres.",
    auth_keyword_label: "Palavra Chave",
    auth_keyword_subtitle: "Necessária para recuperação de senha.",
    auth_forgot_password_button: "Esqueceu a senha?",
    auth_confirm_password_label: "Confirmar Senha",
    auth_error_password_mismatch: "As senhas não coincidem.",
    onboarding_step1_title: "Configure seu perfil",
    onboarding_step1_subtitle: "Sua foto de perfil ajuda as pessoas a reconhecerem você.",
    onboarding_upload_button: "Carregar Foto",
    onboarding_skip_button: "Pular por agora",
    onboarding_next_button: "Avançar",
    onboarding_step2_title: "Descreva quem você é",
    onboarding_step2_subtitle: "Sua bio é a primeira coisa que as pessoas verão no seu perfil.",
    onboarding_bio_placeholder: "Escreva algo sobre você...",
    onboarding_finish_button: "Concluir",
    onboarding_upload_error: "Falha ao carregar a imagem. Verifique suas regras do Firebase Storage e tente novamente.",
    onboarding_finish_error: "Falha ao salvar o perfil. Por favor, tente novamente.",
    firebase_storage_unauthorized_error: "Permissão negada. Por favor, verifique suas regras de segurança do Firebase Storage.",
    edit_profile_title: "Editar Perfil",
    edit_profile_name_label: "Nome",
    edit_profile_bio_label: "Bio",
    edit_profile_change_photo: "Alterar Foto",
    edit_profile_save_button: "Salvar Alterações",
    edit_profile_saving_button: "Salvando...",
    edit_profile_success: "Perfil atualizado com sucesso!",
    edit_profile_error: "Falha ao atualizar o perfil. Tente novamente.",
    image_crop_title: "Cortar Imagem",
    image_crop_save_button: "Salvar",
    search_no_results: "Nenhum usuário encontrado.",
    recovery_modal_title: "Guarde Suas Credenciais!",
    recovery_modal_subtitle: "Guarde sua Hash e Palavra Chave em um local seguro. Elas são essenciais para recuperar o acesso à sua conta se você esquecer sua senha.",
    recovery_modal_hash_label: "Sua Hash de Carteira",
    recovery_modal_keyword_label: "Sua Palavra Chave",
    recovery_modal_copy_button: "Copiar Informações",
    recovery_modal_copied_button: "Copiado!",
    recovery_modal_close_button: "Eu guardei em local seguro",
    forgot_password_title: "Recuperação de Conta",
    forgot_password_step1_title: "Passo 1: Verifique sua Hash",
    forgot_password_hash_placeholder: "Cole sua Hash de Carteira aqui",
    forgot_password_verify_hash_button: "Verificar Hash",
    forgot_password_step2_title: "Passo 2: Confirme sua Palavra Chave",
    forgot_password_keyword_placeholder: "Digite sua palavra chave secreta",
    forgot_password_verify_keyword_button: "Verificar Palavra Chave",
    forgot_password_step3_title: "Passo 3: Defina uma Nova Senha",
    forgot_password_new_password_label: "Nova Senha",
    forgot_password_confirm_password_label: "Confirme a Nova Senha",
    forgot_password_reset_button: "Redefinir Senha",
    forgot_password_success_message: "Senha atualizada com sucesso! Agora você pode fazer login com sua nova senha.",
    forgot_password_back_to_login: "Voltar para o Login",
    forgot_password_error_hash_not_found: "Nenhum usuário encontrado com esta Hash.",
    forgot_password_error_keyword_incorrect: "Palavra chave incorreta. Tente novamente.",
    forgot_password_error_password_mismatch: "As senhas não coincidem.",
    repost_modal_title: "Repostar Sinal",
    repost_modal_repost_button: "Repostar",
    repost_modal_quote_repost_button: "Repostar com comentário",
    repost_modal_quote_placeholder: "Adicione seu comentário...",
    repost_modal_post_button: "Postar",
    settings_title: "Configurações",
    settings_theme_toggle: "Alterar Tema",
    settings_language_toggle: "Alterar Idioma",
    settings_language_pt: "Português",
    settings_language_en: "English",
  },
  en: {
    header_wallet_balance: "VTX",
    header_sign_out: "Sign Out",
    header_search_placeholder: "Search APOLO...",
    dashboard_title: "APOLO Panel",
    dashboard_reset: "Reset",
    dashboard_min_trust: "Min. Trust Score:",
    dashboard_signal_types: "Signal Types",
    dashboard_token_tags: "Token Tags",
    signal_type_NEWS: "News",
    signal_type_ON_CHAIN: "On-Chain",
    signal_type_PROJECT_UPDATE: "Project Update",
    signal_type_RUMOR: "Rumor",
    signal_type_SOCIAL_SENTIMENT: "Social Sentiment",
    create_signal_title_placeholder: "Signal Title...",
    create_signal_content_placeholder: "What's the signal, {name}?",
    create_signal_tags_placeholder: "Add token tags... (e.g., BTC, ETH, SOL)",
    create_signal_post_button: "Post Signal",
    create_signal_analyzing_button: "Posting...",
    feed_loading: "Loading news feed...",
    feed_no_signals: "No signals match your current filters.",
    feed_reset_filters: "Reset Filters",
    error_fetch_feed: "Failed to fetch news feed. Please try again.",
    error_ai_analysis: "AI analysis failed. Please try again.",
    error_follow_update: "Failed to update follow status. Please try again.",
    error_post_signal: "Failed to post signal. Please try again.",
    error_post_comment: "Failed to post comment. Please try again.",
    error_like_update: "Failed to update like status. Please try again.",
    error_repost_update: "Failed to update repost status. Please try again.",
    error_delete_signal: "Failed to delete signal. Please try again.",
    error_translation_failed: "Translation failed. Please try again later.",
    signal_card_trust_score: "Trust Score",
    signal_card_integrity_breakdown: "Integrity Breakdown:",
    signal_card_manipulation_risk: "Manipulation Risk",
    signal_card_scam_potential: "Scam Potential",
    signal_card_factuality: "Factuality",
    signal_card_verified_sources: "Verified Sources",
    signal_card_analyzing: "Integrity analysis in progress...",
    signal_card_request_analysis: "Request Integrity Analysis",
    signal_card_delete_button: "Delete",
    signal_card_delete_confirm: "Are you sure you want to delete this signal? This action cannot be undone.",
    signal_card_translate_button: "Translate",
    signal_card_complex_analysis: "Complex analysis received",
    translating: "Translating...",
    trending_title: "Trending",
    modal_signal_details_title: "Signal Details",
    modal_comments_title: "Comments",
    modal_reply_placeholder: "Post your reply...",
    modal_reply_button: "Reply",
    modal_replying_to: "Replying to",
    modal_cancel_reply: "cancel",
    delete_modal_title: "Confirm Deletion",
    delete_modal_message: "This action cannot be undone. This will permanently delete the signal.",
    delete_modal_confirm: "Delete",
    delete_modal_cancel: "Cancel",
    profile_follow: "Follow",
    profile_following: "Following",
    profile_followers: "Followers",
    profile_posts: "Signals",
    profile_edit: "Edit Profile",
    profile_view_button: "View Profile",
    profile_back_to_feed: "Back to Feed",
    profile_following_stat: "Following",
    profile_no_signals_yet: "{handle} hasn't posted any signals yet.",
    profile_follows_you: "Follows you",
    feed_tab_for_you: "For You",
    feed_tab_following: "Following",
    feed_following_empty_title: "Your feed is quiet...",
    feed_following_empty_subtitle: "Follow creators to see their signals here.",
    feed_following_no_posts_title: "Nothing new for now",
    feed_following_no_posts_subtitle: "The people you follow haven't posted anything yet.",
    notifications_title: "Notifications",
    notifications_empty: "You have no notifications yet.",
    notifications_clear_all: "Clear All",
    notification_like: "liked your signal:",
    notification_comment: "commented on your signal:",
    notification_follow: "started following you.",
    enhancer_button: "Enhance with AI",
    enhancer_button_enhancing: "Enhancing...",
    enhancer_title: "AI Signal Enhancer",
    enhancer_description: "Here are a few AI-powered suggestions based on your idea. Pick one to refine your signal.",
    enhancer_use_suggestion: "Use this suggestion",
    enhancer_error: "Failed to get AI suggestions. Please try again.",
    auth_welcome_title: "Welcome to APOLO",
    auth_welcome_subtitle: "The crypto integrity network. Please sign in to continue.",
    auth_email_label: "Email",
    auth_password_label: "Password",
    auth_login_button: "Sign In",
    auth_signup_button: "Sign Up",
    auth_toggle_to_signup: "Don't have an account?",
    auth_toggle_to_login: "Already have an account?",
    auth_name_label: "Name & Last Name",
    auth_handle_label: "Username (@)",
    auth_error_generic: "An error occurred. Please try again.",
    auth_error_invalid_credentials: "Invalid credentials. Please check your username and password.",
    auth_error_handle_in_use: "This username is already taken.",
    auth_error_weak_password: "Password should be at least 6 characters.",
    auth_keyword_label: "Keyword",
    auth_keyword_subtitle: "Required for password recovery.",
    auth_forgot_password_button: "Forgot password?",
    auth_confirm_password_label: "Confirm Password",
    auth_error_password_mismatch: "Passwords do not match.",
    onboarding_step1_title: "Set up your profile",
    onboarding_step1_subtitle: "Your profile picture helps people recognize you.",
    onboarding_upload_button: "Upload Photo",
    onboarding_skip_button: "Skip for now",
    onboarding_next_button: "Next",
    onboarding_step2_title: "Describe who you are",
    onboarding_step2_subtitle: "Your bio is the first thing people will see on your profile.",
    onboarding_bio_placeholder: "Write something about yourself...",
    onboarding_finish_button: "Finish",
    onboarding_upload_error: "Image upload failed. Check your Firebase Storage rules and try again.",
    onboarding_finish_error: "Failed to save profile. Please try again.",
    firebase_storage_unauthorized_error: "Permission denied. Please check your Firebase Storage security rules.",
    edit_profile_title: "Edit Profile",
    edit_profile_name_label: "Name",
    edit_profile_bio_label: "Bio",
    edit_profile_change_photo: "Change Photo",
    edit_profile_save_button: "Save Changes",
    edit_profile_saving_button: "Saving...",
    edit_profile_success: "Profile updated successfully!",
    edit_profile_error: "Failed to update profile. Please try again.",
    image_crop_title: "Crop Image",
    image_crop_save_button: "Save",
    search_no_results: "No users found.",
    recovery_modal_title: "Save Your Credentials!",
    recovery_modal_subtitle: "Store your Hash and Keyword in a safe place. They are essential to regain access to your account if you forget your password.",
    recovery_modal_hash_label: "Your Wallet Hash",
    recovery_modal_keyword_label: "Your Keyword",
    recovery_modal_copy_button: "Copy Info",
    recovery_modal_copied_button: "Copied!",
    recovery_modal_close_button: "I've saved it safely",
    forgot_password_title: "Account Recovery",
    forgot_password_step1_title: "Step 1: Verify Your Hash",
    forgot_password_hash_placeholder: "Paste your Wallet Hash here",
    forgot_password_verify_hash_button: "Verify Hash",
    forgot_password_step2_title: "Step 2: Confirm Your Keyword",
    forgot_password_keyword_placeholder: "Enter your secret keyword",
    forgot_password_verify_keyword_button: "Verify Keyword",
    forgot_password_step3_title: "Step 3: Set a New Password",
    forgot_password_new_password_label: "New Password",
    forgot_password_confirm_password_label: "Confirm New Password",
    forgot_password_reset_button: "Reset Password",
    forgot_password_success_message: "Password updated successfully! You can now log in with your new password.",
    forgot_password_back_to_login: "Back to Login",
    forgot_password_error_hash_not_found: "No user found with this Hash.",
    forgot_password_error_keyword_incorrect: "Incorrect keyword. Please try again.",
    forgot_password_error_password_mismatch: "Passwords do not match.",
    repost_modal_title: "Repost Signal",
    repost_modal_repost_button: "Repost",
    repost_modal_quote_repost_button: "Quote with comment",
    repost_modal_quote_placeholder: "Add your comment...",
    repost_modal_post_button: "Post",
    settings_title: "Settings",
    settings_theme_toggle: "Toggle Theme",
    settings_language_toggle: "Change Language",
    settings_language_pt: "Português",
    settings_language_en: "English",
  }
};

type Language = 'pt' | 'en';
type Translations = typeof translations.pt;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof Translations, replacements?: Record<string, string>) => string;
  translateSignalType: (type: SignalType) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = useCallback((key: keyof Translations, replacements?: Record<string, string>): string => {
    let translation = translations[language][key] || translations['en'][key] || key;
    if (replacements) {
        Object.keys(replacements).forEach(placeholder => {
            translation = translation.replace(`{${placeholder}}`, replacements[placeholder]);
        });
    }
    return translation;
  }, [language]);

  const translateSignalType = useCallback((type: SignalType): string => {
    return t(`signal_type_${type}` as keyof Translations);
  }, [t]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateSignalType }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};